language: elixir
elixir:
  - 1.4.2

env:
 global:
   - MIX_ENV=test
   - PULL_REQUEST_ID=$TRAVIS_PULL_REQUEST

before_install:
  - "phantomjs --version"
  - "export PATH=$PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH"
  - "phantomjs --version"

before_script:
  - rvm install ruby-2.3.1
  - gem install pronto-credo

script:
  - if [ $PULL_REQUEST_ID != false ]; then pronto run -f github_pr; fi
  - mix coveralls.travis

cache:
 directories:
   — /home/travis/.rvm/
